import React from "react";
import "./News.css";
import NewsCard from "./NewsCard";

function News() {

  return (
    <div className="news">
      <div className="news-container">
        <div className="news-title">
          <h2>FKA Games News</h2>
        </div>
        <NewsCard
          title="News Title"
          date="16 May, 2023"
          content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
          asodpfk adfa lmkal apodkfasp malşsdfmaş asdfmşasldmfş adsfa"
          longContent="Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf"
        />
        <div className="line" />
        <NewsCard
          title="News Title"
          date="16 May, 2023"
          content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
          asodpfk adfa lmkal apodkfasp malşsdfmaş asdfmşasldmfş adsfa"
          longContent="Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf"
        />
        <div className="line" />
        <NewsCard
          title="News Title"
          date="16 May, 2023"
          content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
          asodpfk adfa lmkal apodkfasp malşsdfmaş asdfmşasldmfş adsfa"
          longContent="Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf"
        />
        <div className="line" />
        <NewsCard
          title="News Title"
          date="16 May, 2023"
          content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
          asodpfk adfa lmkal apodkfasp malşsdfmaş asdfmşasldmfş adsfa"
          longContent="Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf"
        />
        <div className="line" />
        <NewsCard
          title="News Title"
          date="16 May, 2023"
          content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
          asodpfk adfa lmkal apodkfasp malşsdfmaş asdfmşasldmfş adsfa"
          longContent="Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. asdf as fasd fasdf asdf asd fsadf asdf asdf sadf asdf asdf asdf ıasjdf oıasdj foaısdjf oıasdjf aoısdj foasıdj foısdj fsıodfj asopdj faspodıjfsadjfsldkşfjaslkdjf klasdj flksadj fşlajdf laşsdjfşlaksdjfşlk sajşlsadjf şlkasdj flkajsdşlf jasdşlfkjasşlfjaşslk djfşlasj şlkasj dflşksdj flşksadjf lşaksdjf şlaskdjf"
        />
      </div>
    </div>
  );
}

export default News;
